import "./globals.css";

import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import Footer from "../components/Footer";
import Header from "../components/Header";
import { ThemeProvider } from "../context/ThemeContext";

const OpenSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next Blog",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body className={`${OpenSans.className} flex flex-col select-none`}>
                <ThemeProvider>
                    <Header />
                    <main className="grow w-full max-w-6xl self-center mt-16 px-6 py-10">
                        {children}
                    </main>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
